/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { IERC20 } from "./@openzeppelin/contracts/token/ERC20/IERC20";
export { IERC20__factory } from "./factories/@openzeppelin/contracts/token/ERC20/IERC20__factory";
export type { VaultAPI } from "./contracts/VaultAPI";
export { VaultAPI__factory } from "./factories/contracts/VaultAPI__factory";
export type { YieldChallenge } from "./contracts/YieldChallenge";
export { YieldChallenge__factory } from "./factories/contracts/YieldChallenge__factory";
